### ISSUE TITLE
Imgur and Lavalink

### ISSUE THREAD

**Issue by KaineWooten** [CriticalFlaw/FlawBOT#36]
Been attempting to redo a discord bot through the flawbot code and I have stumbled upon isssues with `ImgurService.cs` and `LavalinkService.cs`

The errors with Imgur are it isn't able to find certain namespaces for `GallerySortOrder` `TimeWindow` and seems to recognize some of the Imgur  directives in the project

While that's going on in Lavalink it's showing an error with the following line
`AsyncEvent<LavalinkGuildConnection, TrackExceptionEventArgs>` on line 22 or 23 even though it's private readonly varient above it is showing no such errors

Something to also mention that a directive name `Emzi0767` is unable to be called upon / located and is causing me 1 error in `FlawBOT.cs` with `<SecureRandom>`

If you need anymore information let me know and I'll try to help you as best as I can

**Comment by CriticalFlaw** [comment]
It looks like DSharpPlus made changes to some of those functions and they needed to be updated. Should compile now. Thanks

**Comment by KaineWooten** [comment]
Thank you for the reply, but I'm still having issues with errors in `ImgurService.cs` and am unsure if there is a proper fix to it or should I just remove the cs file in the mean time since the `Imgur.API` directives seem to unable to be called upon 
https://i.imgur.com/FF6Y7R3.png

**Comment by CriticalFlaw** [comment]
Did you happen to update the Imgur library to the latest?

**Comment by KaineWooten** [comment]
If 5.0.0 is the latest version then yes I have it updated to the latest, if it's mean to be that then I'm unsure what it could be

**Comment by CriticalFlaw** [comment]
You should revert it. Version 5 of that API library for some reason removed a lot of functionality and is no longer being updated. That's why it isn't updated in the master branch build.

**Comment by KaineWooten** [comment]
Oh, well that's kind of stupid all things considered but it seems to have worked thank you!
